FlowFusion\BlogBundle\Entity\BaseEntity:
    type: mappedSuperclass
    repositoryClass: FlowFusion\BlogBundle\Repository\BaseEntityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    manyToOne:
        createdBy:
            targetEntity: FlowFusion\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_created_by_id:
                    referenceColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        updatedBy:
            targetEntity: FlowFusion\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_updated_by_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
