FlowFusion\BlogBundle\Entity\Category:
    type: entity
    table: ff_blog_category
    repositoryClass: FlowFusion\BlogBundle\Repository\categoryRepository
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        status:
            type: integer
            nullable: false
        show_in_menu:
            type: boolean
            nullable: true
    manyToOne:
        parent:
            targetEntity: Category
            cascade: {  }
            inversedBy: childs
            joinColumns:
                fk_parent_id:
                    referenceColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    oneToMany:
        childs:
            targetEntity: Category
            mappedBy: parent
    manyToMany:
        posts:
            targetEntity: FlowFusion\BlogBundle\Entity\Post
            mappedBy: categories
    lifecycleCallbacks: {  }
