flow_fusion_blog_index:
    path:     /
    defaults: { _controller: FlowFusionBlogBundle:View:index }

flow_fusion_blog_404:
    path:     /notfound
    defaults: { _controller: FlowFusionBlogBundle:View:_404 }

flow_fusion_blog_author_index:
    path:     /author/{username}
    defaults: { _controller: FlowFusionBlogBundle:View:authorIndex }

flow_fusion_blog_category_index:
    path:     /category/{slug}/{id}
    defaults: { _controller: FlowFusionBlogBundle:View:categoryIndex }

flow_fusion_blog_tag_index:
    path:     /tag/{slug}/{id}
    defaults: { _controller: FlowFusionBlogBundle:View:tagIndex }

flow_fusion_blog_post_show:
    path:     /{y}/{m}/{d}/{slug}/{id}
    defaults: { _controller: FlowFusionBlogBundle:View:post }
